apiVersion: v1
kind: Service
metadata:
  name: portal-survey-agent
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: portal-survey-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: portal-survey
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: {{ .Values.agent.service.targetPort }}
      nodePort: {{ .Values.agent.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: portal-survey-agent
    app.kubernetes.io/component: agent
