{{- if .Values.mysql.enabled }}
# ---- MySQL credentials ----
apiVersion: v1
kind: Secret
metadata:
  name: portal-survey-db-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: portal-survey-mysql
    app.kubernetes.io/part-of: portal-survey
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
---
{{- else if .Values.externalDatabase.createSecret }}
# ---- External DB credentials ----
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDatabase.existingSecretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: portal-survey-api
    app.kubernetes.io/part-of: portal-survey
type: Opaque
stringData:
  {{ .Values.externalDatabase.usernameKey }}: {{ .Values.externalDatabase.user | quote }}
  {{ .Values.externalDatabase.passwordKey }}: {{ .Values.externalDatabase.password | quote }}
---
{{- end }}
# ---- Application secrets ----
apiVersion: v1
kind: Secret
metadata:
  name: portal-survey-app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: portal-survey-api
    app.kubernetes.io/part-of: portal-survey
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwt_secret_key | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openai_api_key | quote }}